version: '3'

services:
  nodejs-app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: cipherdba 
      POSTGRES_DB: postgres 
      POSTGRES_HOST: ec2-44-203-160-144.compute-1.amazonaws.com 
      SERVICE_HOST: ec2-3-82-97-232.compute-1.amazonaws.com

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: cipherdba 
      POSTGRES_DB: postgres 
    ports:
      - "5432:5432"
