version: '3'

services:
  nodejs-app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    links:
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cipherdba 
      POSTGRES_DB: postgres 
    ports:
      - "5432:5432"
