version: '3'

services:
  nodejs-app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      POSTGRES_USER: REDACTED 
      POSTGRES_PASSWORD: REDACTED 
      POSTGRES_DB: REDACTED 
      POSTGRES_HOST: REDACTED 
      SERVICE_HOST: REDACTED 

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: REDACTED 
      POSTGRES_PASSWORD: REDACTED 
      POSTGRES_DB: REDACTED 
    ports:
      - "5432:5432"
